env            = "prod"
name_prefix    = "cloudchallenge"
location       = "australiaeast"
swa_location   = "eastasia"                         
cosmos_free_tier  = false                           
cosmos_serverless = true                        
custom_domains = ["zoltanolasz.com", "www.zoltanolasz.com"]
auth_mode  = "oidc"
site_url   = "https://zoltanolasz.com"
